[package]
name = "basic-bin"
version = "0.1.0"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"

[dependencies]
basic-lib = { path = "../basic-lib" }

[package.metadata.nix]
build = true